### ISSUE TITLE
Replication of Toy Example for Deep Ensemble

### ISSUE THREAD

**Issue by lethaiq** [y0ast/deterministic-uncertainty-quantification#1]
Thanks for great paper.

I am trying to replicate the uncertainty plot of Deep Ensemble of the Toy Example but I couldn't get the same plot as shown in Figure 1 of the paper. 

I noticed that we only have the code for DUQ. Can you also share the code for generating the uncertainty plot for Deep Ensemble?

Thanks,

**Comment by y0ast** [comment]
No problem, I've added it.
