### ISSUE TITLE
A question of paper

### ISSUE THREAD

**Issue by timelikeswind** [y0ast/deterministic-uncertainty-quantification#5]
In the figure 2 of the paper, why let uncertain be 
<img src="http://latex.codecogs.com/gif.latex?uncertainty = \exp \left[-\frac{\frac{1}{n}|| \mathbf{W}_{\mathrm{c}} f_{\theta}(\mathbf{x})-\mathbf{e}_{\mathrm{c}}||_{2}^{2}}{2 \sigma^{2}}\right]">?
If <img src="http://latex.codecogs.com/gif.latex?\mathbf{W}_{\mathrm{c}} f_{\theta}(\mathbf{x})"> is very close to the centroid, uncertainty will be bigger in this formula, which is hard to understand.

**Comment by y0ast** [comment]
You're right: that value is between 0 and 1, with 0 being maximum uncertainty and 1 no uncertainty.

We negate it in our evaluation: https://github.com/y0ast/deterministic-uncertainty-quantification/blob/master/utils/evaluate_ood.py#L48 (I'll add this to the figure, thanks!).
