### ISSUE TITLE
Feasibility for object detection

### ISSUE THREAD

**Issue by hantaotao** [y0ast/deterministic-uncertainty-quantification#7]
Hello，Can this method be used for object detection? Have you done relevant experiments? Thank you so much!

**Comment by y0ast** [comment]
Hmm, DUQ cannot be easily extended to regression, so bounding box object detection would be difficult.

We do have a follow up (workshop) paper on semantic segmentation: https://arxiv.org/abs/2111.00079 based on a different but similar method.

**Comment by leyuan-sun** [comment]
> Hmm, DUQ cannot be easily extended to regression, so bounding box object detection would be difficult.
> 
> We do have a follow up (workshop) paper on semantic segmentation: https://arxiv.org/abs/2111.00079 based on a different but similar method.

One object detction network is developed bases on your DUQ, https://ieeexplore.ieee.org/abstract/document/9627771, published on RA-L recently.

I will also try to implment your method on 6D pose regression task.

**Comment by y0ast** [comment]
Thank you for sharing this :)
